services:
  python-dev: # サービス名 (任意)
    build:
      context: . # Dockerfileがあるディレクトリ (カレントディレクトリ)
      dockerfile: Dockerfile
      args:
        POETRY_VERSION: ${POETRY_VERSION}
        POETRY_HOME: ${POETRY_HOME}
        USER_UID: ${USER_UID}
        USERNAME: ${USERNAME}
    container_name: ${CONTAINER_NAME}
    volumes:
      - type: bind
        source: ./src
        target: /home/${USERNAME}
    working_dir: /home/${USERNAME}
    ports:
      - "6274:6274"  # MCPサーバのポートをホストに公開
      - "6277:6277"  # MCPサーバのポートをホストに公開
    tty: true 
    restart: always # コンテナが停止した場合に常に再起動する